const routes = {
  home: '/',
  minimal: '/minimal',
  retro: '/retro',
  swap: '/swap',
  liquidity: '/liquidity',
  liquidityPosition: '/liquidity-position',
  farms: '/farms',
  farmsTwo: '/farms-2',
  createNft: '/create-nft',
  nftDetails: '/nft-details',
  search: '/search',
  notification: '/notification',
  vote: '/vote',
  proposals: '/proposals',
  createProposal: '/proposals/create',
  charts: '/charts',
  profile: '/profile',
  portfolio: '/profile?view=portfolio',
  history: '/profile?view=history',
  classic: '/classic',
  createProject: '/create-project',
  createMrv: '/create-mrv',
  vvbProfile: '/vvb-profile',
  farmerProfile: '/farmer-profile',
  mrvExplore: '/mrv-explore',
  mrvDetails: '/mrv-details',
  projectDetails: '/project-details',
  projectExplore: '/project-explore',
  welcome: '/welcome', // Updated WelcomePage route
};

export default routes;
