name: ACR Cleanup

on:
  schedule:
    # Exécuter le nettoyage tous les dimanches à minuit UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure CLI
        uses: azure/setup-cli@v1
        with:
          version: '2.0.70'

      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Cleanup Old Images
        run: |
          # Variables
          ACR_NAME="${{ secrets.ACR_LOGIN_SERVER }}"
          REPOSITORY_NAME="<your-repository-name>"  # Remplacez par le nom de votre dépôt
          DAYS_OLD=30

          # Liste des images avec leurs dates de création
          images=$(az acr repository show-manifests --name $ACR_NAME --repository $REPOSITORY_NAME --query '[].{Digest: digest, Created: createdTime}' --output tsv)

          # Date actuelle
          current_date=$(date +%s)

          # Boucle pour parcourir les images
          while IFS=$'\t' read -r digest created; do
            # Convertir la date de création en timestamp
            created_date=$(date -d $created +%s)

            # Calculer l'âge de l'image
            age=$(( (current_date - created_date) / 86400 ))

            # Si l'image est plus vieille que le nombre de jours spécifié, la supprimer
            if [ $age -gt $DAYS_OLD ]; then
              echo "Deleting image $digest (created on $created)"
              az acr repository delete --name $ACR_NAME --repository $REPOSITORY_NAME --tag $digest --yes
            fi
          done <<< "$images"
