name: CD ACDR Factory

on:
  workflow_run:
    workflows: ["CI ACDR Factory"]
    types:
      - completed
    conclusions: 
      - success

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: AlderFactory
          images: ${{ secrets.ACR_LOGIN_SERVER }}/acdrfactoryimg:latest
